# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQNS5Yb8MntHgfvCa9V62bMLDaqBxhQ5
"""

# !pip install yfinance

# ============================================================
# Market Data Analysis & PnL Modeling
# ============================================================
# This script:
# - Downloads equity price data (Yahoo Finance via yfinance)
# - Computes returns, PnL/equity curves, volatility, drawdowns
# - Builds an equal-weight portfolio
# - Produces plots + summary tables
# ============================================================

import sys
import subprocess
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -----------------------------
# 0. Ensure yfinance is installed
# -----------------------------
try:
    import yfinance as yf
except ModuleNotFoundError:
    print("yfinance not found. Installing now...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "yfinance"])
    import yfinance as yf

plt.style.use("seaborn-v0_8")


def download_prices(tickers, start_date, end_date):
    """
    Download adjusted close prices using yfinance.
    Returns a DataFrame indexed by date with columns=tickers.
    """
    df = yf.download(
        tickers,
        start=start_date,
        end=end_date,
        auto_adjust=True,
        progress=False,
    )

    # When multiple tickers, columns are multi-index: ('Close', 'AAPL'), etc.
    # We want the Close prices only.
    if isinstance(df.columns, pd.MultiIndex):
        prices = df["Close"].copy()
    else:
        # Single ticker: df is single-level; "Close" is a column
        prices = df[["Close"]].copy()
        prices.columns = tickers

    # Drop rows where all tickers are missing
    prices = prices.dropna(how="all")
    return prices


def compute_drawdowns(equity_curve):
    """
    equity_curve: DataFrame (or Series) of cumulative growth of $1.
    Returns drawdown series/dataframe and max drawdown.
    """
    rolling_max = equity_curve.cummax()
    drawdown = equity_curve / rolling_max - 1.0
    max_drawdown = drawdown.min()
    return drawdown, max_drawdown


def main():
    # -----------------------------
    # 1. User Inputs
    # -----------------------------
    tickers = ["AAPL", "MSFT", "SPY"]
    start_date = "2020-01-01"
    end_date = "2024-01-01"

    # -----------------------------
    # 2. Download Market Data
    # -----------------------------
    prices = download_prices(tickers, start_date, end_date)

    print("\n=== Price Data Preview ===")
    print(prices.head())

    # -----------------------------
    # 3. Compute Daily Returns
    # -----------------------------
    returns = prices.pct_change().dropna()

    print("\n=== Return Summary (Daily) ===")
    print(returns.describe().T[["mean", "std", "min", "max"]])

    # -----------------------------
    # 4. Equity Curves (Growth of $1)
    # -----------------------------
    equity_curve = (1.0 + returns).cumprod()

    ax = equity_curve.plot(figsize=(10, 6), title="Cumulative Returns (Equity Curves)")
    ax.set_ylabel("Growth of $1")
    plt.show()

    # -----------------------------
    # 5. Annualized Volatility
    # -----------------------------
    annualized_vol = returns.std() * np.sqrt(252)

    print("\n=== Annualized Volatility ===")
    print(annualized_vol)

    # -----------------------------
    # 6. Drawdowns + Max Drawdown
    # -----------------------------
    drawdown, max_drawdown = compute_drawdowns(equity_curve)

    print("\n=== Maximum Drawdown (by asset) ===")
    print(max_drawdown)

    ax = drawdown.plot(figsize=(10, 6), title="Drawdowns")
    ax.set_ylabel("Drawdown")
    plt.show()

    # -----------------------------
    # 7. Risk Summary Table (Assets)
    # -----------------------------
    risk_summary = pd.DataFrame({
        "Annualized Volatility": annualized_vol,
        "Maximum Drawdown": max_drawdown
    })

    print("\n=== Risk Summary (Assets) ===")
    print(risk_summary)

    # -----------------------------
    # 8. Equal-Weighted Portfolio
    # -----------------------------
    weights = np.ones(len(tickers)) / len(tickers)

    portfolio_returns = returns.dot(weights)
    portfolio_equity = (1.0 + portfolio_returns).cumprod()

    ax = portfolio_equity.plot(figsize=(10, 6), title="Equal-Weighted Portfolio Equity Curve")
    ax.set_ylabel("Growth of $1")
    plt.show()

    # -----------------------------
    # 9. Portfolio Risk Metrics
    # -----------------------------
    portfolio_vol = portfolio_returns.std() * np.sqrt(252)
    portfolio_drawdown, portfolio_max_dd = compute_drawdowns(portfolio_equity)

    print("\n=== Portfolio Metrics ===")
    print(f"Annualized Volatility: {portfolio_vol:.4f}")
    print(f"Maximum Drawdown:     {portfolio_max_dd:.4f}")

    ax = portfolio_drawdown.plot(figsize=(10, 6), title="Portfolio Drawdown")
    ax.set_ylabel("Drawdown")
    plt.show()

    portfolio_summary = pd.DataFrame({
        "Portfolio Annualized Volatility": [portfolio_vol],
        "Portfolio Maximum Drawdown": [portfolio_max_dd]
    })

    print("\n=== Portfolio Summary Table ===")
    print(portfolio_summary)

    print("\nDone ✅")


if __name__ == "__main__":
    main()